on:
  push:
    branches:
      - main

name: Deploy
jobs:
  deploy:
    name: Deploy
    # Change below line to: `runs-on: ubuntu-latest` if not using self-hosted runners or if it is a public repo.
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: rtCamp/action-deploy-wordpress@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
